<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>71b2847a-6451-41a5-ae11-8c2525e6c3ff</elementGuidId>
    <imagePath></imagePath>
    <name>link_OnboardUs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[4]/div[2]/div[1]/section[2]/div[2]/div[1]/div[2]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'linkElement') and equals(@href,'{{url}}') and equals(@text,'Onboard Us')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#comp-j7ghssjg [data-testid="linkElement"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>linkElement</value>
        <webElementGuid>244efd6f-cafe-41cc-9e99-2723de2770da</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>{{url}}</value>
        <webElementGuid>244efd6f-cafe-41cc-9e99-2723de2770da</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Onboard Us</value>
        <webElementGuid>244efd6f-cafe-41cc-9e99-2723de2770da</webElementGuid>
    </webElementProperties>
</WebElementEntity>