<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c702bd2e-dd52-4dee-8d06-838aa35454bb</elementGuidId>
    <imagePath></imagePath>
    <name>div_designableListOptions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'designable_list_option') and equals(@id,'menuitem-0')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-testid="designable_list"] &gt;&gt; internal:role=option[name="${div_designableListOptions_internalRoleOptionName}"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>designable_list_option</value>
        <webElementGuid>244efd6f-cafe-41cc-9e99-2723de2770da</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>menuitem-0</value>
        <webElementGuid>244efd6f-cafe-41cc-9e99-2723de2770da</webElementGuid>
    </webElementProperties>
</WebElementEntity>