<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9202d076-2513-4a98-98ac-20df75bfe76b</elementGuidId>
    <imagePath></imagePath>
    <name>link_learnMore_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[1]/main[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/section[1]/div[2]/div[1]/section[2]/div[2]/div[1]/div[2]/div[1]/div[5]/div[2]/div[1]/div[1]/div[2]/div[1]/div[3]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#comp-j7gf5qvh &gt; [class="uDW_Qe\ wixui-button\ PlZyDq"]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@data-testid,'linkElement') and equals(@href,'https://mohit3021.wixsite.com/qcitech-solutions/team-4') and equals(@text,'Learn More')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>#comp-j7getfqo [data-testid="linkElement"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>data-testid</name>
        <type>Main</type>
        <value>linkElement</value>
        <webElementGuid>3e85fa11-951f-4089-9e98-cb0a8442189e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>https://mohit3021.wixsite.com/qcitech-solutions/team-4</value>
        <webElementGuid>3e85fa11-951f-4089-9e98-cb0a8442189e</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Learn More</value>
        <webElementGuid>3e85fa11-951f-4089-9e98-cb0a8442189e</webElementGuid>
    </webElementProperties>
</WebElementEntity>